---
- hosts: overcloud
  vars:
    metadata:
      name: Pre-deployment
      description: Validations that run before any deployment
      stage: pre-deployment
- include: ../validations/discovery_diff.yaml
- include: ../validations/undercloud-disk-space.yaml
- include: ../validations/undercloud-ram.yaml
- include: ../validations/undercloud-cpu.yaml
- include: ../validations/undercloud-process-count.yaml
- include: ../validations/512e.yaml
- include: ../validations/network_environment.yaml
- include: ../validations/check-network-gateway.yaml
- include: ../validations/instackenv.yaml
- include: ../validations/rogue-dhcp.yaml
- include: ../validations/ctlplane-ip-range.yaml
